version: '3.9'

services:

  postgres:
    container_name: postgres_container
    image: postgres:10
    environment:
      PGDATA: /data/postgres
    env_file:
      - .env
    volumes:
      - /postgres:/data/postgres
    ports:
      - "3000:5432"
    expose:
      - "5432"
    networks:
      - base_net
    restart: unless-stopped

  api:
    container_name: api
    build:
      context: ./api
    environment:
      DB_HOST: postgres
    env_file:
      - "api/.env"
    ports:
      - '8000:8000'
    networks:
      - base_net
    depends_on:
      - postgres
    restart: unless-stopped

  tgbot:
    container_name: bot
    build:
      context: ./bot
    environment:
      HOST: api
    env_file:
      - "bot/.env"
    networks:
      - base_net
    restart: unless-stopped
    depends_on:
      - postgres
      - api


networks:
  base_net:
    driver: bridge